# Generated by Django 4.2.7 on 2023-11-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeries', '0002_remove_stock_industry_remove_stock_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_short',
            field=models.CharField(default='error', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fundFamily',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='longBusinessSummary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='longName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
