# Generated by Django 4.2.7 on 2023-11-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeries', '0003_remove_stock_id_stock_stock_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_short',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
