# Generated by Django 4.2.7 on 2023-11-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeries', '0004_alter_stock_stock_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_short',
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='error', max_length=50, primary_key=True, serialize=False),
        ),
    ]
