# Generated by Django 4.2.7 on 2023-11-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeries', '0005_remove_stock_stock_short_alter_stock_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fundFamily',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='legalType',
            new_name='sector',
        ),
        migrations.AddField(
            model_name='stock',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
