# Generated by Django 4.2.7 on 2023-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeries', '0006_delete_industry_rename_fundfamily_stock_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
